# -*- coding: utf-8 -*-
# Card conditions (cond) are the archive's own European Portuguese from content.js.
# Everything else here is machine translated and needs a native speaker's pass.

CARD_PT = {
 'shell-cream': dict(
   hint1='Como usarias o Shell Cream em 2040?',
   hint2='Se as conchas deixarem de se formar, o que mais poderia um corpo vestir?',
   pill='sobrevive &#224; era &#225;cida...',
   caps='O oceano n&#227;o quer saber do teu interior.',
   tag='Mas n&#243;s queremos.',
   q='Ent&#227;o do que precisa Esposende em vez disso?',
   src='Acidifica&#231;&#227;o do oceano &middot; sistema de afloramento ib&#233;rico',
   example='O Shell Cream &#233; feito a partir do &#225;cido, para quem tem as conchas a dissolver-se.',
   cond=('&#192; medida que o oceano absorve mais carbono, o seu pH desce, e os animais que constroem '
         'conchas perdem o carbonato de que precisam para as construir. As conchas ficam mais finas e '
         'algumas come&#231;am a dissolver-se. Fomos &#224; procura de conchas nesta costa e volt&#225;mos quase sem nada.')),
 'acid-tabs': dict(
   hint1='Que outras pastilhas vai a &#225;gua de Esposende precisar para combater o &#225;cido?',
   hint2='Se as florestas de algas desaparecerem, o que venderias ao mar?',
   pill='dissolve-te com dignidade.',
   caps='Mant&#233;m o teu &#225;cido sob controlo. Agora com sabor a sulfureto de dimetilo!',
   tag='O oceano nunca mais te deixa.',
   q='O que venderias a um mar que est&#225; a azedar?',
   src='Descida do pH &middot; florestas de sarga&#231;o e algas &middot; carbono azul',
   example='Os Acid Tabs engarrafam o mar azedo, para quem o quer sob controlo.',
   cond=('O mesmo problema pelo outro lado. O longo registo da descida do pH no sistema de afloramento '
         'ib&#233;rico cobre esta costa, e o norte de Portugal, incluindo Esposende, &#233; a sua parte mais '
         'exposta. A acidifica&#231;&#227;o &#233; uma amea&#231;a s&#233;ria ao sarga&#231;o e &#224;s florestas de algas daqui.')),
 'sexy-dunes': dict(
   hint1='Como seriam as Sexy Dunes em 2040?',
   hint2='O que faria as pessoas deixarem de largar coisas na areia?',
   pill='as dunas n&#227;o mentem, querida!',
   caps='A investiga&#231;&#227;o mostra que dunas com ar sexy t&#234;m menos 25% de probabilidade de receber lixo.',
   tag='N&#243;s tratamos de ti.',
   q='O que faria as pessoas deixarem as dunas em paz?',
   src='Eros&#227;o costeira &middot; lixo &middot; micropl&#225;sticos',
   example='O Sexy Dunes vende a duna como objeto de desejo, para que ningu&#233;m lhe deixe lixo.',
   cond=('A costa norte portuguesa apresenta alguns dos maiores riscos de eros&#227;o e de galgamento do '
         'pa&#237;s, e as dunas suportam-nos a par do lixo e de tudo o resto que l&#225; deixamos. O pl&#225;stico '
         'deixado na areia torna-se micropl&#225;stico na &#225;gua.')),
 'sargassum-city': dict(
   hint1='Se a Sargassum City fosse constru&#237;da, quem viveria l&#225;?',
   hint2='O que nos venderia o sarga&#231;o de volta, se pudesse?',
   pill='@a grande vida do mar',
   caps='Leva-me at&#233; &#224; Sargassum City. Onde a erva &#233; verde e os peixes s&#227;o bonitos.',
   tag='Garante j&#225; a tua melhor localiza&#231;&#227;o.',
   q='A quem deve pertencer o sarga&#231;o?',
   src='Sarga&#231;o como habitat &middot; sarga&#231;o como mercadoria',
   example='A Sargassum City vende apartamentos na alga, a quem gostar do bairro.',
   cond=('O sarga&#231;o &#233; cada vez mais utilizado e ser&#225; provavelmente mais comercializado, como recurso, '
         'para oxig&#233;nio, para material, para a prateleira da farm&#225;cia. &#201; tamb&#233;m, antes disso, um '
         'habitat de que a vida marinha precisa para simplesmente existir. A alga j&#225; era uma cidade, '
         'com habitantes, antes de algu&#233;m pensar em vend&#234;-la.')),
 'deluxe-o2': dict(
   hint1='Quanto custaria o Deluxe O&#8322; em 2040?',
   hint2='Se a &#225;gua deixasse de produzir oxig&#233;nio, o que ocuparia o seu lugar?',
   pill='tamb&#233;m vais fazer oooh...',
   caps='Est&#225;s farta do teu oxig&#233;nio terrestre de sempre, vindo daquelas &#225;rvores verdes feias?',
   tag='Respira melhor, querida!',
   q='Se a &#225;gua deixasse de respirar, o que venderias?',
   src='Oxig&#233;nio azul &middot; fotoss&#237;ntese &middot; mares mais quentes',
   example='O Deluxe O2 engarrafa o oxig&#233;nio que a alga produz, para quem est&#225; farto do ar comum.',
   cond=('O sarga&#231;o e as algas marinhas produzem oxig&#233;nio por fotoss&#237;ntese, a outra metade da '
         'hist&#243;ria do carbono. Esse ciclo &#233; real, e a &#225;gua mais quente torna-o menos est&#225;vel: '
         'altera-se e, em condi&#231;&#245;es de flora&#231;&#227;o densa, pode inverter-se e retirar oxig&#233;nio.')),
}

UI_PT = {
 'corp':'she tells entity', 'answered':'de 5 respondidas',
 'openerWord':'she tells entity', 'openerName':'ela<br><em>escuta</em>',
 'openerPill':'n&#227;o h&#225; resposta certa',
 'openerCaps':'Cinco produtos na prateleira. O oceano continua a pedir mais um.',
 'openerTag':'&#201; a tua vez, querida.',
 'openerLabel':'como isto funciona',
 'openerCond':('A frente de cada carta mostra um produto que imagin&#225;mos, a partir da nossa investiga&#231;&#227;o em Esposende durante o Sea Shells, She Tells, o nosso projeto para a resid&#234;ncia S+T+ARTS Aqua Motion, acolhida pelo Rio Neiva.<br><br>Agora &#233; a tua vez. Escolhe uma, fica a conhec&#234;-la, e cria uma grava&#231;&#227;o de voz para a nossa Transmiss&#227;o Eterna. Escolhe gravar um produto futuro especulativo para Esposende, ou uma mem&#243;ria de &#225;gua que te venha &#224; ideia.<br><br>Funciona sozinha, e funciona melhor a dois: um l&#234; a carta em voz alta, o outro responde.'),
 'openerSrc':'Cinco cartas no baralho &middot; responde por qualquer ordem',
 'openerQ':'Come&#231;amos?', 'openerCta':'d&#225;-me uma carta',
 'openerDeal':'tirar uma carta', 'openerDealSub':'qualquer uma das cinco',
 'openerFoot':'Nada para instalar. A tua voz entra na transmiss&#227;o eterna.',
 'flip':'toca para virar &rarr;', 'begin':'toca para come&#231;ar &rarr;',
 'hotlineCall':'Ligar para a linha de apoio', 'hotlineLab':'linha de apoio',
 'hotIn_en':'em ingl&#234;s', 'hotIn_pt':'em portugu&#234;s',
 'hotlineConnect':'a ligar&#8230;', 'hotlineFail':'a linha est&#225; em baixo',
 'hotlineHang':'Desligar', 'hotlinePlay':'Ouvir', 'hotlinePause':'Pausa',
 'deckTitle':'o baralho', 'deckSub':'Tira a de cima, ou baralha para outra carta.',
 'reshuffle':'baralhar', 'takeTop':'tirar a carta de cima',
 'cardsLeft':'cartas restantes', 'lastCard':'&#250;ltima carta', 'putBack':'devolver',
 'condLabel':'o que est&#225; mesmo a acontecer', 'yourTurn':'&#233; a tua vez',
 'remember':'recordar', 'rememberSub':'algo verdadeiro',
 'invent':'inventar', 'inventSub':'o sexto produto',
 'foot':'Vai direto para a transmiss&#227;o. Trinta segundos chegam.',
 'ingTitle':'Acaba esta frase', 'ingLead':'Em 2040, Esposende vai precisar de',
 'ingSub':'Um produto. Pode ser rid&#237;culo.', 'like':'como &ldquo;',
 'hint':'sem ideias? d&#225;-me uma pista', 'hint2':'outra pista', 'hintDone':'j&#225; n&#227;o h&#225; mais ajuda',
 'hintMat':'pensa nisto', 'hintBuy':'ou nisto', 'hint3':'e mais uma', 'hintMade':'ou faz com isto', 'ready':'j&#225; sei o que &#233;',
 'consentTitle':'antes de falares', 'consentH':'A tua voz vai ser p&#250;blica',
 'consentP1':'<b>Entra na transmiss&#227;o eterna</b>, onde qualquer pessoa a pode ouvir, e onde pode ser escutada atrav&#233;s de um shellphone caseiro. Diz apenas o que te sentes bem a partilhar.',
 'consentP2':'N&#227;o vamos treinar nenhuma IA com a tua voz, nem us&#225;-la para nada al&#233;m desta obra.',
 'consentP3':'Mudaste de ideias? Escreve-nos em duas semanas e retiramo-la:',
 'consentP4':'Pedimos o teu email para te avisarmos quando a tua grava&#231;&#227;o entrar na transmiss&#227;o.',
 'consentOk':'compreendo, quero gravar', 'consentNo':'agora n&#227;o',
 'scriptInvent':'L&#234; isto em voz alta', 'scriptRemember':'Fala-nos da &#225;gua',
 'blkName':'o nome', 'blkMade':'do que &#233; feito', 'blkFor':'para quem &#233;', 'blkBecause':'o que est&#225; a correr mal',
 'blkWhere':'onde estavas', 'blkLike':'como era', 'blkWith':'com quem, ou sozinha', 'blkStayed':'o que ainda v&#234;s',
 'scriptHint':'Preenche os espa&#231;os &#224; medida que vais. Trinta segundos ou mais, e quanto mais melhor.',
 'scriptHintR':'Come&#231;a por onde quiseres. Trinta segundos ou mais, e quanto mais melhor.',
 'tapRec':'toca para gravar', 'recording':'a gravar', 'tapStop':'toca para parar',
 'again':'gravar outra vez', 'useThis':'usar esta',
 'tagTitle':'&#250;ltima coisa',
 'tagSub':'A transmiss&#227;o toca o que combina com o tempo em Esposende agora. Para que tipo de dia &#233; o teu futuro?',
 'skip':'saltar', 'sendTitle':'&#250;ltimo passo',
 'sendSub':'Para te avisarmos quando entrar na transmiss&#227;o.',
 'emailLabel':'o teu email', 'send':'enviar para a transmiss&#227;o', 'back':'voltar',
 'thanksTitle':'j&#225; est&#225; na transmiss&#227;o', 'thanksProduct':'O teu produto para ', 'thanksMemory':'A tua mem&#243;ria para ',
 'thanksRest':' est&#225; a caminho. Enviamos-te um email quando puder ser ouvido.', 'nextCard':'pr&#243;xima carta',
 'doneTitle':'a linha est&#225; completa',
 'doneSub':'Cinco condi&#231;&#245;es respondidas. Os teus produtos entram na transmiss&#227;o eterna, onde podem ser ouvidos atrav&#233;s de um shellphone caseiro.',
 'madeTitle':'O que fizeste', 'playAgain':'jogar outra vez', 'howWas':'como correu?', 'catalogue':'ver o cat&#225;logo',
 'noEmail':'escreve o teu email primeiro', 'badEmail':'esse email n&#227;o parece certo',
 'noRec':'ainda n&#227;o h&#225; grava&#231;&#227;o', 'sending':'a enviar...',
 'errServer':'algo correu mal. tenta outra vez.', 'errNet':'n&#227;o foi poss&#237;vel chegar &#224; transmiss&#227;o.',
 'noMic':'acesso ao microfone negado. verifica as defini&#231;&#245;es do navegador.',
 'mlNote':'* Tradu&#231;&#227;o autom&#225;tica. Em revis&#227;o.',
}

UI_EN = {
 'corp':'she tells entity', 'answered':'of 5 answered',
 'openerWord':'she tells entity', 'openerName':'she<br><em>listens</em>',
 'openerPill':'there is no right answer',
 'openerCaps':'Five products on the shelf. The ocean keeps asking for one more.',
 'openerTag':'Your turn, darling.',
 'openerLabel':'how this works',
 'openerCond':('The front of each card shows a product we imagined, based on our research in Esposende during Sea Shells, She Tells, our project for the S+T+ARTS Aqua Motion residency, hosted by Rio Neiva.<br><br>It is now your turn. Pick one, learn about it, and create a voice recording for our Eternal Stream. Choose to record a speculative future product for Esposende, or a water memory it brings to mind.<br><br>Works on your own, and works better with two: one reads the card out loud, the other answers.'),
 'openerSrc':'Five cards in the deck &middot; answer them in any order',
 'openerQ':'Shall we begin?', 'openerCta':'deal me in',
 'openerDeal':'draw a card', 'openerDealSub':'any of the five',
 'openerFoot':'Nothing to install. Your voice joins the eternal stream.',
 'flip':'tap to turn &rarr;', 'begin':'tap to begin &rarr;',
 'hotlineCall':'Call the hotline', 'hotlineLab':'hotline',
 'hotIn_en':'in english', 'hotIn_pt':'in portuguese',
 'hotlineConnect':'connecting&#8230;', 'hotlineFail':'the line is down',
 'hotlineHang':'Hang up', 'hotlinePlay':'Play', 'hotlinePause':'Pause',
 'deckTitle':'the deck', 'deckSub':'Take the one on top, or shuffle for a different card.',
 'reshuffle':'reshuffle', 'takeTop':'take the top card',
 'cardsLeft':'cards left', 'lastCard':'last card', 'putBack':'put it back',
 'condLabel':'what is actually happening', 'yourTurn':'your turn',
 'remember':'remember', 'rememberSub':'something real',
 'invent':'invent', 'inventSub':'the sixth product',
 'foot':'Goes straight to the stream. Thirty seconds is plenty.',
 'ingTitle':'Finish this sentence', 'ingLead':'In 2040, Esposende will need',
 'ingSub':'One product. It is allowed to be ridiculous.', 'like':'like &ldquo;',
 'hint':'stuck? give me a hint', 'hint2':'another hint', 'hintDone':'that is all the help there is',
 'hintMat':'think about this', 'hintBuy':'or this', 'hint3':'one more', 'hintMade':'or make it out of this', 'ready':'i know what it is',
 'consentTitle':'before you speak', 'consentH':'Your voice will be public',
 'consentP1':'<b>It joins the eternal stream</b>, where anyone can hear it, and where it can be listened to through a DIY shell phone. Only say what you are happy for other people to hear.',
 'consentP2':'We will not train any AI on your voice, and we will not use it for anything beyond this artwork.',
 'consentP3':'Changed your mind? Email us within two weeks and we will take it out:',
 'consentP4':'We ask for your email so we can tell you when your recording joins the stream.',
 'consentOk':'i understand, let me record', 'consentNo':'not this time',
 'scriptInvent':'Just read this out loud', 'scriptRemember':'Tell us about the water',
 'blkName':'the name', 'blkMade':'what it is made of', 'blkFor':'who needs it', 'blkBecause':'what is going wrong',
 'blkWhere':'where you were', 'blkLike':'what it was like', 'blkWith':'who, or nobody', 'blkStayed':'the thing you still see',
 'scriptHint':'Fill in the gaps as you go. Thirty seconds or more, and the longer the better.',
 'scriptHintR':'Start anywhere. Thirty seconds or more, and the longer the better.',
 'tapRec':'tap to record', 'recording':'recording', 'tapStop':'tap to stop',
 'again':'record again', 'useThis':'use this one',
 'tagTitle':'one last thing',
 'tagSub':'The stream plays what matches the weather in Esposende right now. What kind of day is your future for?',
 'skip':'skip this', 'sendTitle':'last step',
 'sendSub':'So we can tell you when it joins the stream.',
 'emailLabel':'your email', 'send':'send it to the stream', 'back':'back',
 'thanksTitle':'it is in the stream', 'thanksProduct':'Your product for ', 'thanksMemory':'Your memory for ',
 'thanksRest':' is on its way. We will email you when it can be heard.', 'nextCard':'next card',
 'doneTitle':'the line is complete',
 'doneSub':'Five conditions answered. Your products join the eternal stream, where they can be heard through a DIY shell phone.',
 'madeTitle':'What you made', 'playAgain':'play again', 'howWas':'how was that?', 'catalogue':'see the catalogue',
 'noEmail':'please enter your email first', 'badEmail':"that email doesn't look right",
 'noRec':'no recording yet, tap the circle first', 'sending':'sending...',
 'errServer':'something went wrong. please try again.', 'errNet':'could not reach the stream. check your connection.',
 'noMic':'microphone access denied. check your browser settings.',
 'mlNote':'',
}

# machine translated, to be checked by a native speaker
MAT_PT = [
 ('sarga&#231;o','apanhado nesta costa h&#225; s&#233;culos, e ainda a crescer'),
 ('redes de pesca','j&#225; remendadas cem vezes, e ainda se podem remendar'),
 ('linha biodegrad&#225;vel','feita para voltar ao mar de onde veio'),
 ('areia das dunas','segura pelo estorno, e por quem passa ao lado'),
 ('uma concha','a forma que a &#225;gua ensinou um animal a construir'),
 ('bioplástico','sarga&#231;o fervido numa panela at&#233; ficar como vidro mole'),
 ('&#225;gua do rio','o Neiva, a levar a terra devagar at&#233; ao mar'),
 ('sal','o que o sol deixa, e o que conserva'),
 ('junco','cana da margem, tecida aqui muito antes do pl&#225;stico e ainda hoje'),
 ('fio de cobre','transporta um sinal, e transporta uma voz'),
]

BUY_PT = [
 'uma turista que nunca viu uma concha viva',
 'o rio Neiva, que tem opini&#245;es sobre o que chega ao mar',
 'uma crian&#231;a nascida em Esposende este ano',
 'a &#250;ltima pessoa que se lembra da apanha do sarga&#231;o',
 'um peixe &#224; procura de onde viver',
 'a c&#226;mara municipal, com or&#231;amento e uma costa',
 'a tua av&#243;, que nadou aqui',
 'o pr&#243;prio oceano',
]
