# -*- coding: utf-8 -*-
# Card conditions (cond) are the archive's own European Portuguese from content.js.
# Everything else here is machine translated and needs a native speaker's pass.

CARD_PT = {
 'shell-cream': dict(
   hint1='Como usarias o Shell Cream em 2040?',
   hint2='Se construir uma concha ficasse mais dif&#237;cil, o que ajudaria?',
   pill='sobrevive &#224; era &#225;cida...',
   caps='O oceano n&#227;o quer saber do teu interior.',
   tag='Mas n&#243;s queremos.',
   q='Ent&#227;o do que precisa Esposende em vez disso?',
   src='Acidifica&#231;&#227;o do oceano &middot; construir uma concha',
   example='O Shell Cream &#233; feito a partir do &#225;cido, para quem tem dificuldade em manter a forma.',
   cond=('&#192; medida que o oceano absorve mais carbono, vai ficando mais &#225;cido. Isso &#233; uma m&#225; not&#237;cia para todos os animais que constroem conchas: quanto mais &#225;cida a &#225;gua, mais dif&#237;cil &#233; fazer uma.')),
 'acid-tabs': dict(
   hint1='Que outras pastilhas vai a &#225;gua de Esposende precisar para combater o &#225;cido?',
   hint2='O que darias ao mar antes de o &#225;cido chegar?',
   pill='dissolve-te com dignidade.',
   caps='Mant&#233;m o teu &#225;cido sob controlo. Agora com sabor a sulfureto de dimetilo!',
   tag='O oceano nunca mais te deixa.',
   q='O que venderias a um mar que est&#225; a azedar?',
   src='Calor e &#225;cido em conjunto &#183; um problema que ainda est&#225; para vir',
   example='Os Acid Tabs engarrafam o mar azedo, para quem o quer sob controlo.',
   cond=('O calor e o &#225;cido v&#234;m do mesmo carbono. O mar absorve a maior parte do calor a mais que ele ret&#233;m, e um quarto do pr&#243;prio carbono, o que torna a &#225;gua mais &#225;cida. A nossa investiga&#231;&#227;o mostra que, nesta costa, a acidifica&#231;&#227;o &#233; mais um problema que ainda est&#225; para vir.')),
 'sexy-dunes': dict(
   hint1='Como seriam as Sexy Dunes em 2040?',
   hint2='O que faria as pessoas deixarem de largar coisas na areia?',
   pill='as dunas n&#227;o mentem, querida!',
   caps='A investiga&#231;&#227;o mostra que dunas com ar sexy t&#234;m menos 25% de probabilidade de receber lixo.',
   tag='N&#243;s tratamos de ti.',
   q='O que faria as pessoas deixarem as dunas em paz?',
   src='Dunas &#183; lixo &#183; micropl&#225;sticos',
   example='O Sexy Dunes vende a duna como objeto de desejo, para que ningu&#233;m lhe deixe lixo.',
   cond=('As dunas seguram a costa, entre o mar e a terra, e carregam tudo o que l&#225; deixamos. O pl&#225;stico deixado na areia desfaz-se em micropl&#225;stico na &#225;gua.')),
 'sargassum-city': dict(
   hint1='Se a Sargassum City fosse constru&#237;da, quem viveria l&#225;?',
   hint2='O que nos venderia o sarga&#231;o de volta, se pudesse?',
   pill='@a grande vida do mar',
   caps='Leva-me at&#233; &#224; Sargassum City. Onde a erva &#233; verde e os peixes s&#227;o bonitos.',
   tag='Garante j&#225; a tua melhor localiza&#231;&#227;o.',
   q='O que construirias para os peixes vizinhos?',
   src='Florestas de lamin&#225;rias &#183; as algas do sarga&#231;o como habitat',
   example='A Sargassum City vende apartamentos na alga, a quem gostar do bairro.',
   cond=('O sarga&#231;o &#233; uma mistura de algas, entre elas as lamin&#225;rias, trazida pelo mar para a costa. Antes de chegar &#224; areia, era uma floresta: ao largo do norte de Portugal, no limite sul onde algumas lamin&#225;rias conseguem viver, as florestas marinhas abrigam, alimentam e embalam in&#250;meras vidas marinhas. A alga j&#225; era uma cidade, com os seus pr&#243;prios habitantes, muito antes de algu&#233;m pensar em vend&#234;-la.')),
 'deluxe-o2': dict(
   hint1='Quanto custaria o Deluxe O&#8322; em 2040?',
   hint2='Como trarias as bolhas de volta?',
   pill='tamb&#233;m vais fazer oooh...',
   caps='Est&#225;s farta do teu oxig&#233;nio terrestre de sempre, vindo daquelas &#225;rvores verdes feias?',
   tag='Respira melhor, querida!',
   q='O que tornaria o oceano mais fresco?',
   src='As algas produzem oxig&#233;nio &#183; mares mais quentes &#183; menos oxig&#233;nio',
   example='O Deluxe O2 engarrafa o oxig&#233;nio que a alga produz, para quem est&#225; farto do ar comum.',
   cond=('As algas desta costa, entre elas as lamin&#225;rias, produzem oxig&#233;nio enquanto crescem e retiram carbono ao mesmo tempo. O mar est&#225; a aquecer, e a &#225;gua quente ret&#233;m menos oxig&#233;nio, tal como uma bebida deixada ao sol perde o g&#225;s.')),
}

UI_PT = {
 'corp':'she tells entity', 'answered':'de 5 respondidas',
 'openerWord':'she tells entity', 'openerName':'ela<br><em>escuta</em>',
 'openerPill':'n&#227;o h&#225; resposta certa',
 'openerCaps':'Cinco produtos na prateleira. O oceano continua a pedir mais um.',
 'openerTag':'&#201; a tua vez, querida.',
 'openerLabel':'o que &#233; isto',
 'openerCond':('Um jogo de cartas do Sea Shells, She Tells, o nosso projeto para a resid&#234;ncia S+T+ARTS Aqua Motion, acolhida pelo Rio Neiva, em Esposende.'),
 'openerSrc':'Cinco cartas no baralho &middot; responde por qualquer ordem',
 'openerQ':'Come&#231;amos?', 'openerCta':'d&#225;-me uma carta',
 'openerDeal':'mostra-me como', 'openerDealSub':'quatro passos, depois uma carta',
 'howTitle':'como se joga',
 'howLead':'Cinco produtos de 2040, feitos pela She Tells Entity para outros corpos oce&#226;nicos. Cada um &#233; uma piada sobre algo que est&#225; mesmo a acontecer na &#225;gua de Esposende.',
 'how1':'<b>1 &middot; tira.</b> Escolhe uma carta. A frente &#233; um an&#250;ncio. Liga para a linha de apoio para ouvires o discurso de venda.',
 'how2':'<b>2 &middot; vira.</b> Toca na carta. O verso conta-te o que se passa mesmo na &#225;gua daqui.',
 'how3':'<b>3 &middot; responde.</b> <em>Recorda</em> uma mem&#243;ria de &#225;gua tua, ou <em>inventa</em> o sexto produto acabando uma frase: <em>Em 2040, Esposende vai precisar de&#8230;</em> Depois grava a tua voz.',
 'how4':'<b>4 &middot; ouve.</b> A tua voz junta-se &#224; transmiss&#227;o eterna, e o tempo de Esposende decide quando toca.',
 'howNote':'Joga a solo, ou melhor a dois: uma pessoa l&#234; a carta, a outra responde.',
 'howGo':'percebi, d&#225;-me uma carta',
 'openerFoot':'Nada para instalar. A tua voz entra na transmiss&#227;o eterna.',
 'flip':'toca para virar &rarr;', 'begin':'toca para come&#231;ar &rarr;',
 'hotlineCall':'Ligar para a linha de apoio', 'hotlineLab':'linha de apoio',
 'hotIn_en':'em ingl&#234;s', 'hotIn_pt':'em portugu&#234;s',
 'hotlineConnect':'a ligar&#8230;', 'hotlineFail':'a linha est&#225; em baixo',
 'hotlineHang':'Desligar', 'hotlinePlay':'Ouvir', 'hotlinePause':'Pausa',
 'deckTitle':'o baralho', 'deckSub':'Tira a de cima, ou baralha para outra carta.',
 'reshuffle':'baralhar', 'takeTop':'tirar a carta de cima',
 'cardsLeft':'cartas restantes', 'lastCard':'&#250;ltima carta', 'putBack':'devolver',
 'condLabel':'o que est&#225; mesmo a acontecer', 'yourTurn':'&#233; a tua vez',
 'remember':'recordar', 'rememberSub':'algo verdadeiro',
 'invent':'inventar', 'inventSub':'o sexto produto',
 'foot':'Vai direto para a transmiss&#227;o. Trinta segundos chegam.',
 'ingTitle':'Acaba esta frase', 'ingLead':'Em 2040, Esposende vai precisar de',
 'ingSub':'Um produto. Pode ser rid&#237;culo.', 'like':'como &ldquo;',
 'hint':'sem ideias? d&#225;-me uma pista', 'hint2':'outra pista', 'hintDone':'j&#225; n&#227;o h&#225; mais ajuda',
 'hintMat':'pensa nisto', 'hintBuy':'ou nisto', 'hint3':'e mais uma', 'hintMade':'ou faz com isto', 'ready':'j&#225; sei o que &#233;',
 'consentTitle':'antes de falares', 'consentH':'A tua voz vai ser p&#250;blica',
 'consentP1':'<b>Entra na transmiss&#227;o eterna</b>, onde qualquer pessoa a pode ouvir, e onde pode ser escutada atrav&#233;s de um shellphone caseiro. Diz apenas o que te sentes bem a partilhar.',
 'consentP2':'N&#227;o vamos treinar nenhuma IA com a tua voz, nem us&#225;-la para nada al&#233;m desta obra.',
 'consentP3':'Mudaste de ideias? Escreve-nos em duas semanas e retiramo-la:',
 'consentP4':'Pedimos o teu email para te avisarmos quando a tua grava&#231;&#227;o entrar na transmiss&#227;o.',
 'consentOk':'compreendo, quero gravar', 'consentNo':'agora n&#227;o',
 'scriptInvent':'L&#234; isto em voz alta', 'scriptRemember':'Fala-nos da &#225;gua',
 'blkName':'o nome', 'blkMade':'do que &#233; feito', 'blkFor':'para quem &#233;', 'blkBecause':'o que est&#225; a correr mal',
 'blkWhere':'onde estavas', 'blkLike':'como era', 'blkWith':'com quem, ou sozinha', 'blkStayed':'o que ainda v&#234;s',
 'scriptHint':'Preenche os espa&#231;os &#224; medida que vais. Trinta segundos ou mais, e quanto mais melhor.',
 'scriptHintR':'Come&#231;a por onde quiseres. Trinta segundos ou mais, e quanto mais melhor.',
 'tapRec':'toca para gravar', 'recording':'a gravar', 'tapStop':'toca para parar',
 'again':'gravar outra vez', 'useThis':'usar esta',
 'tagTitle':'&#250;ltima coisa',
 'tagSub':'A transmiss&#227;o toca o que combina com o tempo em Esposende agora. Para que tipo de dia &#233; o teu futuro?',
 'skip':'saltar', 'sendTitle':'&#250;ltimo passo',
 'sendSub':'Para te avisarmos quando entrar na transmiss&#227;o.',
 'emailLabel':'o teu email', 'send':'enviar para a transmiss&#227;o', 'back':'voltar',
 'thanksTitle':'j&#225; est&#225; na transmiss&#227;o', 'thanksProduct':'O teu produto para ', 'thanksMemory':'A tua mem&#243;ria para ',
 'thanksRest':' est&#225; a caminho. Enviamos-te um email quando puder ser ouvido.', 'nextCard':'pr&#243;xima carta',
 'doneTitle':'a linha est&#225; completa',
 'doneSub':'Cinco condi&#231;&#245;es respondidas. Os teus produtos entram na transmiss&#227;o eterna, onde podem ser ouvidos atrav&#233;s de um shellphone caseiro.',
 'madeTitle':'O que fizeste', 'playAgain':'jogar outra vez', 'howWas':'como correu?', 'catalogue':'ver o cat&#225;logo',
 'noEmail':'escreve o teu email primeiro', 'badEmail':'esse email n&#227;o parece certo',
 'noRec':'ainda n&#227;o h&#225; grava&#231;&#227;o', 'sending':'a enviar...',
 'errServer':'algo correu mal. tenta outra vez.', 'errNet':'n&#227;o foi poss&#237;vel chegar &#224; transmiss&#227;o.',
 'noMic':'acesso ao microfone negado. verifica as defini&#231;&#245;es do navegador.',
 'mlNote':'* Tradu&#231;&#227;o autom&#225;tica. Em revis&#227;o.',
}

UI_EN = {
 'corp':'she tells entity', 'answered':'of 5 answered',
 'openerWord':'she tells entity', 'openerName':'she<br><em>listens</em>',
 'openerPill':'there is no right answer',
 'openerCaps':'Five products on the shelf. The ocean keeps asking for one more.',
 'openerTag':'Your turn, darling.',
 'openerLabel':'what this is',
 'openerCond':('A card game from Sea Shells, She Tells, our project for the S+T+ARTS Aqua Motion residency, hosted by Rio Neiva in Esposende.'),
 'openerSrc':'Five cards in the deck &middot; answer them in any order',
 'openerQ':'Shall we begin?', 'openerCta':'deal me in',
 'openerDeal':'show me how', 'openerDealSub':'four steps, then a card',
 'howTitle':'how to play',
 'howLead':'Five products from 2040, made by the She Tells Entity for other ocean bodies. Each one is a joke about something really happening in the water of Esposende.',
 'how1':'<b>1 &middot; draw.</b> Pick a card. The front is an advert. Call the hotline on it to hear the pitch.',
 'how2':'<b>2 &middot; turn.</b> Tap the card. The back tells you what is really going on in the water here.',
 'how3':'<b>3 &middot; answer.</b> <em>Remember</em> a water memory of your own, or <em>invent</em> the sixth product by finishing one sentence: <em>In 2040, Esposende will need&#8230;</em> Then record your voice.',
 'how4':'<b>4 &middot; listen.</b> Your voice joins the eternal stream, and Esposende&#8217;s weather decides when it plays.',
 'howNote':'Play alone, or better with two: one reads the card, the other answers.',
 'howGo':'got it, deal me in',
 'openerFoot':'Nothing to install. Your voice joins the eternal stream.',
 'flip':'tap to turn &rarr;', 'begin':'tap to begin &rarr;',
 'hotlineCall':'Call the hotline', 'hotlineLab':'hotline',
 'hotIn_en':'in english', 'hotIn_pt':'in portuguese',
 'hotlineConnect':'connecting&#8230;', 'hotlineFail':'the line is down',
 'hotlineHang':'Hang up', 'hotlinePlay':'Play', 'hotlinePause':'Pause',
 'deckTitle':'the deck', 'deckSub':'Take the one on top, or shuffle for a different card.',
 'reshuffle':'reshuffle', 'takeTop':'take the top card',
 'cardsLeft':'cards left', 'lastCard':'last card', 'putBack':'put it back',
 'condLabel':'what is actually happening', 'yourTurn':'your turn',
 'remember':'remember', 'rememberSub':'something real',
 'invent':'invent', 'inventSub':'the sixth product',
 'foot':'Goes straight to the stream. Thirty seconds is plenty.',
 'ingTitle':'Finish this sentence', 'ingLead':'In 2040, Esposende will need',
 'ingSub':'One product. It is allowed to be ridiculous.', 'like':'like &ldquo;',
 'hint':'stuck? give me a hint', 'hint2':'another hint', 'hintDone':'that is all the help there is',
 'hintMat':'think about this', 'hintBuy':'or this', 'hint3':'one more', 'hintMade':'or make it out of this', 'ready':'i know what it is',
 'consentTitle':'before you speak', 'consentH':'Your voice will be public',
 'consentP1':'<b>It joins the eternal stream</b>, where anyone can hear it, and where it can be listened to through a DIY shell phone. Only say what you are happy for other people to hear.',
 'consentP2':'We will not train any AI on your voice, and we will not use it for anything beyond this artwork.',
 'consentP3':'Changed your mind? Email us within two weeks and we will take it out:',
 'consentP4':'We ask for your email so we can tell you when your recording joins the stream.',
 'consentOk':'i understand, let me record', 'consentNo':'not this time',
 'scriptInvent':'Just read this out loud', 'scriptRemember':'Tell us about the water',
 'blkName':'the name', 'blkMade':'what it is made of', 'blkFor':'who needs it', 'blkBecause':'what is going wrong',
 'blkWhere':'where you were', 'blkLike':'what it was like', 'blkWith':'who, or nobody', 'blkStayed':'the thing you still see',
 'scriptHint':'Fill in the gaps as you go. Thirty seconds or more, and the longer the better.',
 'scriptHintR':'Start anywhere. Thirty seconds or more, and the longer the better.',
 'tapRec':'tap to record', 'recording':'recording', 'tapStop':'tap to stop',
 'again':'record again', 'useThis':'use this one',
 'tagTitle':'one last thing',
 'tagSub':'The stream plays what matches the weather in Esposende right now. What kind of day is your future for?',
 'skip':'skip this', 'sendTitle':'last step',
 'sendSub':'So we can tell you when it joins the stream.',
 'emailLabel':'your email', 'send':'send it to the stream', 'back':'back',
 'thanksTitle':'it is in the stream', 'thanksProduct':'Your product for ', 'thanksMemory':'Your memory for ',
 'thanksRest':' is on its way. We will email you when it can be heard.', 'nextCard':'next card',
 'doneTitle':'the line is complete',
 'doneSub':'Five conditions answered. Your products join the eternal stream, where they can be heard through a DIY shell phone.',
 'madeTitle':'What you made', 'playAgain':'play again', 'howWas':'how was that?', 'catalogue':'see the catalogue',
 'noEmail':'please enter your email first', 'badEmail':"that email doesn't look right",
 'noRec':'no recording yet, tap the circle first', 'sending':'sending...',
 'errServer':'something went wrong. please try again.', 'errNet':'could not reach the stream. check your connection.',
 'noMic':'microphone access denied. check your browser settings.',
 'mlNote':'',
}

# machine translated, to be checked by a native speaker
MAT_PT = [
 ('sarga&#231;o','apanhado nesta costa h&#225; s&#233;culos, e ainda a crescer'),
 ('redes de pesca','j&#225; remendadas cem vezes, e ainda se podem remendar'),
 ('linha biodegrad&#225;vel','feita para voltar ao mar de onde veio'),
 ('areia das dunas','segura pelo estorno, e por quem passa ao lado'),
 ('uma concha','a forma que a &#225;gua ensinou um animal a construir'),
 ('bioplástico','sarga&#231;o fervido numa panela at&#233; ficar como vidro mole'),
 ('&#225;gua do rio','o Neiva, a levar a terra devagar at&#233; ao mar'),
 ('sal','o que o sol deixa, e o que conserva'),
 ('junco','cana da margem, tecida aqui muito antes do pl&#225;stico e ainda hoje'),
 ('fio de cobre','transporta um sinal, e transporta uma voz'),
]

BUY_PT = [
 'uma turista que nunca viu uma concha viva',
 'o rio Neiva, que tem opini&#245;es sobre o que chega ao mar',
 'uma crian&#231;a nascida em Esposende este ano',
 'a &#250;ltima pessoa que se lembra da apanha do sarga&#231;o',
 'um peixe &#224; procura de onde viver',
 'a c&#226;mara municipal, com or&#231;amento e uma costa',
 'a tua av&#243;, que nadou aqui',
 'o pr&#243;prio oceano',
]
